/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as MediaRouteImport } from './routes/media'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAppointmentsRouteImport } from './routes/admin/appointments'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminDoctorAddRouteImport } from './routes/admin/doctor-add'
import { Route as AdminDoctorsRouteImport } from './routes/admin/doctors'
import { Route as AdminPatientsRouteImport } from './routes/admin/patients'
import { Route as AdminPharmacyRouteImport } from './routes/admin/pharmacy'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DoctorDashboardRouteImport } from './routes/doctor/dashboard'
import { Route as DoctorProfileRouteImport } from './routes/doctor/profile'
import { Route as DoctorRegisterRouteImport } from './routes/doctor/register'
import { Route as PatientDashboardRouteImport } from './routes/patient/dashboard'
import { Route as AdminDoctorEditIdRouteImport } from './routes/admin/doctor-edit.$id'
import { Route as AdminPatientViewIdRouteImport } from './routes/admin/patient-view.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDoctorAddRoute = AdminDoctorAddRouteImport.update({
  id: '/doctor-add',
  path: '/doctor-add',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPharmacyRoute = AdminPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
  id: '/doctor/dashboard',
  path: '/doctor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/doctor/profile',
  path: '/doctor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRegisterRoute = DoctorRegisterRouteImport.update({
  id: '/doctor/register',
  path: '/doctor/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/patient/dashboard',
  path: '/patient/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDoctorEditIdRoute = AdminDoctorEditIdRouteImport.update({
  id: '/doctor-edit/$id',
  path: '/doctor-edit/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPatientViewIdRoute = AdminPatientViewIdRouteImport.update({
  id: '/patient-view/$id',
  path: '/patient-view/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/media': typeof MediaRoute
  '/services': typeof ServicesRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/doctor-add': typeof AdminDoctorAddRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/pharmacy': typeof AdminPharmacyRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/register': typeof DoctorRegisterRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/doctor-edit/$id': typeof AdminDoctorEditIdRoute
  '/admin/patient-view/$id': typeof AdminPatientViewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/media': typeof MediaRoute
  '/services': typeof ServicesRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/doctor-add': typeof AdminDoctorAddRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/pharmacy': typeof AdminPharmacyRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/register': typeof DoctorRegisterRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/admin/doctor-edit/$id': typeof AdminDoctorEditIdRoute
  '/admin/patient-view/$id': typeof AdminPatientViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/media': typeof MediaRoute
  '/services': typeof ServicesRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/doctor-add': typeof AdminDoctorAddRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/pharmacy': typeof AdminPharmacyRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/register': typeof DoctorRegisterRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/doctor-edit/$id': typeof AdminDoctorEditIdRoute
  '/admin/patient-view/$id': typeof AdminPatientViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/doctors'
    | '/media'
    | '/services'
    | '/admin/appointments'
    | '/admin/blog'
    | '/admin/dashboard'
    | '/admin/doctor-add'
    | '/admin/doctors'
    | '/admin/patients'
    | '/admin/pharmacy'
    | '/admin/reports'
    | '/admin/settings'
    | '/auth/login'
    | '/blog/$slug'
    | '/doctor/dashboard'
    | '/doctor/profile'
    | '/doctor/register'
    | '/patient/dashboard'
    | '/admin/'
    | '/admin/doctor-edit/$id'
    | '/admin/patient-view/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/doctors'
    | '/media'
    | '/services'
    | '/admin/appointments'
    | '/admin/blog'
    | '/admin/dashboard'
    | '/admin/doctor-add'
    | '/admin/doctors'
    | '/admin/patients'
    | '/admin/pharmacy'
    | '/admin/reports'
    | '/admin/settings'
    | '/auth/login'
    | '/blog/$slug'
    | '/doctor/dashboard'
    | '/doctor/profile'
    | '/doctor/register'
    | '/patient/dashboard'
    | '/admin'
    | '/admin/doctor-edit/$id'
    | '/admin/patient-view/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/doctors'
    | '/media'
    | '/services'
    | '/admin/appointments'
    | '/admin/blog'
    | '/admin/dashboard'
    | '/admin/doctor-add'
    | '/admin/doctors'
    | '/admin/patients'
    | '/admin/pharmacy'
    | '/admin/reports'
    | '/admin/settings'
    | '/auth/login'
    | '/blog/$slug'
    | '/doctor/dashboard'
    | '/doctor/profile'
    | '/doctor/register'
    | '/patient/dashboard'
    | '/admin/'
    | '/admin/doctor-edit/$id'
    | '/admin/patient-view/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogsRoute: typeof BlogsRoute
  ContactRoute: typeof ContactRoute
  DoctorsRoute: typeof DoctorsRoute
  MediaRoute: typeof MediaRoute
  ServicesRoute: typeof ServicesRoute
  AuthLoginRoute: typeof AuthLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DoctorDashboardRoute: typeof DoctorDashboardRoute
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorRegisterRoute: typeof DoctorRegisterRoute
  PatientDashboardRoute: typeof PatientDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/doctor-add': {
      id: '/admin/doctor-add'
      path: '/doctor-add'
      fullPath: '/admin/doctor-add'
      preLoaderRoute: typeof AdminDoctorAddRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pharmacy': {
      id: '/admin/pharmacy'
      path: '/pharmacy'
      fullPath: '/admin/pharmacy'
      preLoaderRoute: typeof AdminPharmacyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/dashboard': {
      id: '/doctor/dashboard'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof DoctorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/doctor/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/register': {
      id: '/doctor/register'
      path: '/doctor/register'
      fullPath: '/doctor/register'
      preLoaderRoute: typeof DoctorRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/dashboard': {
      id: '/patient/dashboard'
      path: '/patient/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/doctor-edit/$id': {
      id: '/admin/doctor-edit/$id'
      path: '/doctor-edit/$id'
      fullPath: '/admin/doctor-edit/$id'
      preLoaderRoute: typeof AdminDoctorEditIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/patient-view/$id': {
      id: '/admin/patient-view/$id'
      path: '/patient-view/$id'
      fullPath: '/admin/patient-view/$id'
      preLoaderRoute: typeof AdminPatientViewIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDoctorAddRoute: typeof AdminDoctorAddRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminPharmacyRoute: typeof AdminPharmacyRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDoctorEditIdRoute: typeof AdminDoctorEditIdRoute
  AdminPatientViewIdRoute: typeof AdminPatientViewIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDoctorAddRoute: AdminDoctorAddRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminPharmacyRoute: AdminPharmacyRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDoctorEditIdRoute: AdminDoctorEditIdRoute,
  AdminPatientViewIdRoute: AdminPatientViewIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogsRoute: BlogsRoute,
  ContactRoute: ContactRoute,
  DoctorsRoute: DoctorsRoute,
  MediaRoute: MediaRoute,
  ServicesRoute: ServicesRoute,
  AuthLoginRoute: AuthLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  DoctorDashboardRoute: DoctorDashboardRoute,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorRegisterRoute: DoctorRegisterRoute,
  PatientDashboardRoute: PatientDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
